version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dbnetwork

  phpmyadmin:
    container_name: mphpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:8080"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    networks:
      - dbnetwork

networks:
  dbnetwork:
